changelog:
  categories:             # リリースノートのカテゴリ設定
    - title: Enhancement  # リリースノートへ「Enhancement」というカテゴリを作成
      labels:
        - enhancement     # 「Enhancement」へ掲載するPRのラベルを指定
    - title: Bug Fixes
      labels:
        - bug
        - fixes
  exclude:                # リリースノートの除外設定
    labels:               # 除外するラベル
      - dependencies
    authors:              # 除外するPR作成者
      - dependabot