name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - run: |
          go build -ldflags "-X main.version=${VERSION}" -o "${RUNNER_TEMP}/example" go/example/main.go
      - run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release upload "${VERSION}" "${RUNNER_TEMP}/example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
