name: Workflow Design
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  log:
    name: Log
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Debug log
        run: echo "::debug::This is a debug log"

      - name: Tracing Log
        run: |
          set -x
          date
          hostname
