name: WOrkflow Design
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::This is a debug log"
