name: Workflow Design
on: pull_request
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  log:
    name: Log
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Debug log
        run: echo "::debug::This is a debug log"

      - name: Tracing Log
        run: | # Bashのトレーシングオプションを有効化し実行したコマンドをログ出力
          set -x
          date
          hostname

      - name: Group Log
        run: | 
          echo "::group::Show env variables"
          printenv
          echo "::endgroup::"

      - name: Mask Log
        run: |
          echo "::add-mask::${PASSWORD}"
          echo "${PASSWORD}"
        env:
          PASSWORD: SuperSecretValue
      
      - name: Annotation Message
        run: |
          echo "::error::This is an error"
          echo "::warning::This is an warning"
          echo "::notice::This is an notice"

      - name: Job Summary
        run: |
          cat >> "${GITHUB_STEP_SUMMARY}" << 'EOF'
          ## Example Title :rocket:
          - first line
          - second line
          EOF